version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Europe/Helsinki"
    groups:
      aws-cdk:
        patterns:
          - "aws-cdk"
          - "aws-cdk-lib"
          - "constructs"
          - "@aws-cdk/aws-apigatewayv2-alpha"
          - "@aws-cdk/aws-apigatewayv2-integrations-alpha"
